import { describe, expect, it } from "vitest";
import { isTranscriptName, transcriptWords } from "./transcript";

const VTT = `WEBVTT

NOTE
Generated by Zoom

1
00:00:01.000 --> 00:00:04.000
Charlie Wang: So which courses are you taking this year?

2
00:00:04.500 --> 00:00:09.000
<v Sam L>Advanced functions, calculus, physics, chem, English and computer science.</v>

3
00:00:09.500 --> 00:00:12.000
Charlie Wang: And the target is Waterloo software engineering, ninety-five average.
`;

const SRT = `1
00:00:01,000 --> 00:00:04,000
Charlie Wang: Unit 3 test was 31 out of 40.

2
00:00:04,500 --> 00:00:06,000
Charlie Wang: Unit 3 test was 31 out of 40.
`;

describe("transcriptWords", () => {
  it("keeps the spoken lines of a WebVTT file and drops headers, cue numbers, timestamps and speaker labels", () => {
    expect(transcriptWords(VTT)).toBe(
      [
        "So which courses are you taking this year?",
        "Advanced functions, calculus, physics, chem, English and computer science.",
        "And the target is Waterloo software engineering, ninety-five average.",
      ].join("\n"),
    );
  });
  it("reads SRT and collapses repeated cues", () => {
    expect(transcriptWords(SRT)).toBe("Unit 3 test was 31 out of 40.");
  });
  it("keeps a growing live caption once, as its last full line", () => {
    expect(transcriptWords("A: the test\nA: the test was on Friday\nA: the test was on Friday and went well")).toBe("the test was on Friday and went well");
  });
  it("leaves plain text alone apart from blank lines and labels", () => {
    expect(transcriptWords("Goal: Waterloo SE\n\nMHF4U 92%\r\nTests 50%")).toBe("Waterloo SE\nMHF4U 92%\nTests 50%");
  });
});

describe("isTranscriptName", () => {
  it("accepts vtt, srt and txt in any case", () => {
    expect(isTranscriptName("lesson.VTT")).toBe(true);
    expect(isTranscriptName("lesson.srt")).toBe(true);
    expect(isTranscriptName("notes.txt")).toBe(true);
    expect(isTranscriptName("photo.jpg")).toBe(false);
  });
});
